from datetime import datetime, timezone
import json
from app.extensions import db


class DemandForecast(db.Model):
    """Time-series demand forecast projection generated by historical sales models."""
    __tablename__ = 'demand_forecasts'

    id = db.Column(db.Integer, primary_key=True)
    product_id = db.Column(db.Integer, db.ForeignKey('products.id', ondelete='CASCADE'), nullable=False, index=True)
    seller_id = db.Column(db.Integer, db.ForeignKey('seller_profiles.id', ondelete='CASCADE'), nullable=False, index=True)
    
    forecast_date = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), nullable=False, index=True)
    horizon_days = db.Column(db.Integer, default=14, nullable=False)
    forecast_model = db.Column(db.String(50), default='holt_winters_hybrid', nullable=False)
    
    current_stock = db.Column(db.Integer, nullable=False)
    predicted_demand_total = db.Column(db.Integer, nullable=False)
    predicted_daily_rate = db.Column(db.Float, nullable=False)
    confidence_interval_low = db.Column(db.Integer, nullable=False)
    confidence_interval_high = db.Column(db.Integer, nullable=False)
    
    stockout_predicted = db.Column(db.Boolean, default=False, nullable=False)
    estimated_days_to_stockout = db.Column(db.Float, nullable=True)
    recommended_reorder_qty = db.Column(db.Integer, default=0, nullable=False)
    daily_projections = db.Column(db.Text, nullable=False, default='[]')
    
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    product = db.relationship('Product', back_populates='forecasts')
    seller = db.relationship('SellerProfile')

    def get_daily_projections_list(self):
        try:
            return json.loads(self.daily_projections or '[]')
        except Exception:
            return []

    def set_daily_projections_list(self, projections):
        self.daily_projections = json.dumps(projections if isinstance(projections, list) else [])

    def to_dict(self):
        return {
            'id': self.id,
            'product_id': self.product_id,
            'product_title': self.product.title if self.product else None,
            'product_sku': self.product.sku if self.product else None,
            'seller_id': self.seller_id,
            'forecast_date': self.forecast_date.isoformat() if self.forecast_date else None,
            'horizon_days': self.horizon_days,
            'forecast_model': self.forecast_model,
            'current_stock': self.current_stock,
            'predicted_demand_total': self.predicted_demand_total,
            'predicted_daily_rate': round(self.predicted_daily_rate, 2),
            'confidence_interval_low': self.confidence_interval_low,
            'confidence_interval_high': self.confidence_interval_high,
            'stockout_predicted': self.stockout_predicted,
            'estimated_days_to_stockout': self.estimated_days_to_stockout,
            'recommended_reorder_qty': self.recommended_reorder_qty,
            'daily_projections': self.get_daily_projections_list()
        }


class ForecastEvaluation(db.Model):
    """Backtesting accuracy evaluation metrics (MAPE, RMSE, MAE) for forecasting models."""
    __tablename__ = 'forecast_evaluations'

    id = db.Column(db.Integer, primary_key=True)
    product_id = db.Column(db.Integer, db.ForeignKey('products.id', ondelete='CASCADE'), nullable=False, index=True)
    model_name = db.Column(db.String(50), nullable=False)
    mape = db.Column(db.Float, nullable=False)
    rmse = db.Column(db.Float, nullable=False)
    mae = db.Column(db.Float, nullable=False)
    sample_points = db.Column(db.Integer, nullable=False)
    evaluated_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
